### ISSUE TITLE
How to configure alembic to use `render_as_batch=True` 

### ISSUE THREAD

**Issue by jlariza** [davidism/flask-alembic#2]
Good day,

I need to use alembic `render_as_batch` feature. However, I tried using 

```
ALEMBIC_CONTEXT = {
    "render_as_batch": True
}
```

and it did not work. What am I missing? how may I enable this feature?

Thank you

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. The given configuration gets passed through to the migration context, and a migration generated with it contains the `with op.batch_alter_table` block.
